# Configuration for Alacritty, the GPU enhanced terminal emulator.

import:
  - ~/.config/alacritty/everforest.yml


window:
  #dimensions:
  #  columns: 0
  #  lines: 0

  #position:
  #  x: 0
  #  y: 0

  padding:
    x: 10
    y: 10

  #opacity: 1.0

  #startup_mode: Windowed

  #title: Alacritty

  #dynamic_title: true

  #class:
    # Application instance name
    #instance: Alacritty
    # General application class
    #general: Alacritty

#scrolling:
  #history: 10000
  #multiplier: 3

font:
  #normal:
    #family: monospace
    #style: Regular
  #bold:
    #family: monospace
    #style: Bold
  #italic:
    #family: monospace
    #style: Italic
  #bold_italic:
    #family: monospace
    #style: Bold Italic
  size: 18.0
  #offset:
  #  x: 0
  #  y: 0

  #glyph_offset:
  #  x: 0
  #  y: 0

#selection:
  #semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>\t"
  #save_to_clipboard: false

#cursor:
  #style:
    #shape: Block
    #blinking: Off
  #vi_mode_style: None
  #blink_interval: 750
  #blink_timeout: 5
  #unfocused_hollow: true
  #thickness: 0.15
#live_config_reload: true

#shell:
#  program: /bin/bash
#  args:
#    - --login

#working_directory: None
